### ISSUE TITLE
[Bug] TypeError: is_visible() missing 1 required positional argument: 'paths'

### ISSUE THREAD

**Issue by Kristinita** [braver/SideBarTools#12]
### 1. Summary

**If** I use SideBarTools **and** SideBarEnhancements,

    I get stack trace in console.

### 2. Settings

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**Package:**
The latest stable version of SideBarTools and SideBarEnhancements for Sublime Text 3

### 3. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install SideBarTools and SideBarEnhancements → I restart Sublime Text → <kbd>Ctrl+Shift+P</kbd>.

### 4. Expected behavior

**If** I disable SideBarTools **or** SideBarEnhancements,

    no stack trace in console.

### 5. Actual behavior

```python
key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 720, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 722, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 720, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 722, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 720, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 722, in is_visible_
    ret = self.is_visible()
TypeError: is_visible() missing 1 required positional argument: 'paths'

```

Thanks.

**Comment by braver** [comment]
> I use SideBarTools and SideBarEnhancements

Yeah, don't do that. There are probably conflicting settings files so the wrong commands are called or passed the wrong arguments. There is very little guarding against conflicting packages and this combination just doesn't make sense.

**Comment by Kristinita** [comment]
> Yeah, don't do that. There are probably conflicting settings files so the wrong commands are called or passed the wrong arguments. There is very little guarding against conflicting packages and this combination just doesn't make sense.

Please, add it to `README.MD`.

Thanks.
