### ISSUE TITLE
Remove the "forked from SideBarEnhancements-org/SideBarEnhancements" in the Github page's description

### ISSUE THREAD

**Issue by mandx** [braver/SideBarTools#15]
Since #2, this repo is no longer a fork of "SideBarEnhancements". Now is just the original inspiration :)

**Comment by braver** [comment]
I looked into it before and there is no way to achieve this from git or the GitHub UI. Apparently you need to contact support to detach the fork, so I sent them a message. We'll see what happens.

**Comment by braver** [comment]
It's done!
