### ISSUE TITLE
Consider opening the duplicated file after duplication

### ISSUE THREAD

**Issue by adael** [braver/SideBarTools#17]
I think it would be useful if after duplicating a single file (through the duplicate command), the new one opens directly in a new tab.

If you consider to merge this functionality I can make a PR.

**Comment by braver** [comment]
Not a bad idea. One mistake I tend to make is that the view represents the base file, not the new duplicate. I think it would be nice to open a transient view of the new file. We'll just have to try it and see if it works well.

**Comment by braver** [comment]
Well, that was easy, should've done that ages ago 😁
