### ISSUE TITLE
Feature Request: ability to modify some default items

### ISSUE THREAD

**Issue by unknownuser88** [braver/SideBarTools#18]
it would be nice if user can customize some default commands for example replace "new file" menu with custom command like this
`{ "caption": "New File", "command": "advanced_new_file_new_at", "args": {"dirs": []} }`
if I add it to Main.sublime-menu it show 2 menu items with same name but I need only one

**Comment by braver** [comment]
You don't need this or any other package to customise the defaults, Sublime supports this out of the box: https://www.sublimetext.com/docs/3/packages.html

You can use the [resource viewer package](https://packagecontrol.io/packages/PackageResourceViewer) to copy the `Side Bar.sublime-menu` from the Default package to `Packages/Default/Side Bar.sublime-menu`. Anything you change in that file will override the default commands.

**Comment by unknownuser88** [comment]
Can you please help me a little ?
I can't find where is Default package on my machine (ubuntu 16.04)
