### ISSUE TITLE
Feature Request: Duplicate file: show full path so it can be duplicated to different path

### ISSUE THREAD

**Issue by sharkooon** [braver/SideBarTools#21]
It would be nice when duplicating a file to have a full path instead only filename.
<img width="453" alt="duplicate" src="https://user-images.githubusercontent.com/533123/39447405-ee700b52-4cc1-11e8-981b-9e8d3d5f33fa.png">

"Move to" does have a full path, would be nice to have this also for "Duplicate" file. Then it is possible to duplicate to another folder.
<img width="553" alt="rename" src="https://user-images.githubusercontent.com/533123/39447387-df938258-4cc1-11e8-9d32-bcc10386dc2d.png">

**Comment by braver** [comment]
Ah, yes. I tend to do the two step thing, but like that would be super handy.

**Comment by sharkooon** [comment]
I never touched python before, but it was easy to fix it by myself.
I created a pull request ;)

**Comment by braver** [comment]
fixed via #22
