### ISSUE TITLE
Copy relative path provides unexpected result

### ISSUE THREAD

**Issue by rpbaptist** [braver/SideBarTools#23]
I added the following key binding:

```
  { "keys": ["ctrl+shift+c"], "command": "side_bar_copy_relative_path", "args": { "paths": [] } },
```

If I have sublime opening the following directory:

`~/code/company/project`

I use relative path copy for a file:

`~/code/company/project/app/models/user.rb`

The result will be `project/app/models/user.rb` where I would exepct `app/models/user.rb`.

Perhaps my expectation is wrong, but is there a way to append the `paths` argument in my keybinding so It will provide the path I expect?

**Comment by braver** [comment]
There seems to be something wrong with how we build the relative paths when there are multiple root directories. The `commonprefix` gives unexpected results, which leads to buggy results, and if you copy relative paths for a file that *isn't* in the first root directory it still tries to make a path relative to that first root directory.

**Comment by braver** [comment]
Life would be easier with python 3.7 and `os.path.commonpath`, but our solution was a bit sloppy anyway and the next release should fix this.
