### ISSUE TITLE
Installed with package manager but not showing

### ISSUE THREAD

**Issue by BarbzYHOOL** [braver/SideBarTools#24]
I installed the program and I have this "SideBarTools.sublime-package" in ".config/sublime-text-3/Installed Packages" (on linux)

How am I supposed to install it?

And what is the plugin for those nice icons in your screenshot? and for the green "+" for the lines?

**Comment by braver** [comment]
Do you have other packages installed that maybe conflict? Anything logged in the console?

The icons in the sidebar are from [FileIcons](https://packagecontrol.io/packages/FileIcons), the green “+” is from [GitGutter](https://packagecontrol.io/packages/GitGutter).

**Comment by BarbzYHOOL** [comment]
```
DPI scale: 1
startup, version: 3170 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/username
packages path: /home/username/.config/sublime-text-3/Packages
state path: /home/username/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/username/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.466249
startup time: 0.705811
first paint time: 0.710189
Unable to fetch update url contents
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin ApplySyntax.ApplySyntax
reloading plugin ApplySyntax.support
reloading plugin EditorConfig.EditorConfig
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarTools.SideBar
reloading plugin User.auto_close_free_trial_popu
plugins loaded
Package Control: No updated packages
ApplySyntax: Warning: 'file_name' keyword is deprecated and will be removed in the future.

```

:( dunno what to do

 (thank you for other plugins names)

**Comment by braver** [comment]
I don’t see anything wrong. Perhaps reset everything and start over?

https://www.sublimetext.com/docs/3/revert.html

🤷🏼‍♂️

**Comment by BarbzYHOOL** [comment]
I installed manually, same result.

Am I supposed to install something else and then right click on the sidebar's file and that's it??

I never solved any problem by resetting lol, + I installed sublimetext recently and have very few plugins, but well I might try. Note: I just installed fileicons and there is no change in the sidebar lol (but my other plugins work fine, just stuff on the sidebar is not)

**Comment by braver** [comment]
Yeah, just install and it should add some options to the right-click-menu of the sidebar.

**Comment by braver** [comment]
Have a screenshot?

**Comment by BarbzYHOOL** [comment]
Can't take a screenshot when rightclicking lol

The options are "Close / Close others / Close Others below / New file / Open file" seems like default ones.

Also I just installed a simple package for highlighting syntaxes and it works fine but all packages related to the sidebar are not working o_0 I don't even know where to look or ask (sorry to bother you if you can't do anything)

**Comment by BarbzYHOOL** [comment]
Hmm is it normal that when I click on "Browse packages" it opens:

     /home/username/.config/sublime-text-3/Packages

And not:

     /home/username/.config/sublime-text-3/Packages/user

?

**Comment by braver** [comment]
Yes, “user” is also a “package” and it should only contain settings and overrides, not other packages. If you install packages, put them in “packages”, otherwise you’ll have weird issues.

You could try asking on the forums, because I don’t really know how to debug this..

**Comment by BarbzYHOOL** [comment]
Ok I reset and it didn't solve anything as I guessed :'(

EDIT: ok the issue was this (second answer) https://stackoverflow.com/questions/28167587/sidebar-enhancement-plugin-installed-but-not-working

Just not using it right, I knew it was weird lol

**Comment by braver** [comment]
Oh, yeah, that package is total crap when it comes to things like this.
