### ISSUE TITLE
[Suggestion] Move with drag and drop

### ISSUE THREAD

**Issue by BarbzYHOOL** [braver/SideBarTools#26]
Would really love this feature

**Comment by braver** [comment]
Sure, great idea, but there is no API for this. Sublime Text needs to do work in Core for anything like this to work. And that's not something they're likely to ever create. Sorry!

**Comment by BarbzYHOOL** [comment]
I suspected this :(

"And that's not something they're likely to ever create."

why?

**Comment by braver** [comment]
Well they never expressed interest enough to expect this particular feature to ever make it to the top of the list. It's just a small team. Also notice that no real file interaction is available in the sidebar by default (hence this package). Never say never, but it's just not something they're likely to do.

**Comment by BarbzYHOOL** [comment]
ok :( but that would save a lot of precious seconds, damn them
