### ISSUE TITLE
[Suggestion] Right click on folder - Open in Finder

### ISSUE THREAD

**Issue by diego898** [braver/SideBarTools#29]
It would be great if right-clicking on a folder in the sidebar allowed you to open the folder in finder.

**Comment by braver** [comment]
It would be clearer if SideBarTools did that, but there is a package that already does. From the README:

> If you're looking for "Reveal in Finder/Explorer" for directories, [Open in Default Application][2] does that too.

**Comment by diego898** [comment]
thanks @braver
