### ISSUE TITLE
Fantastic package!

### ISSUE THREAD

**Issue by moodmosaic** [braver/SideBarTools#31]
As with your other packages (FileIcons, Solarized) I like the simplicity you put in, and the fact that everything just works out-of-the-box! :heart_eyes: :rocket:

**Comment by braver** [comment]
❤️ 

Thanks man! Makes my day 👍

**Comment by moodmosaic** [comment]
It's guys like you and packages like yours that also keep Sublime Text alive and kicking. (FWIW, I'm working on syntax highlighting stuff, e.g. https://github.com/sublimehq/Packages/pull/2225)

Have a great day :sun_with_face:
