### ISSUE TITLE
[Suggestion] Reveal in Sidebar on Tab focus / Open file

### ISSUE THREAD

**Issue by andremacola** [braver/SideBarTools#36]
Is it possible to implement this feature?

For example, like: https://packagecontrol.io/packages/SyncedSideBar

Unfortunately SyncedSideBar is no longer maintained and not work with ST4

**Comment by braver** [comment]
It's outside the focus of SideBarTools currently. I'd prefer to try and update/fix SyncedSideBar instead of trying to absorb it. It's good to have different packages for different things.
