### ISSUE TITLE
Deleting a folder should also remove it from Project

### ISSUE THREAD

**Issue by bhanubais** [braver/SideBarTools#38]
If we delete a folder from sidebar, Would it not be deleted from project also?
Yes it works. But only for a folder that is under main folder. 
If you remove your root folder then It doesn't remove it from project.
You must remove it again by right clicking on main folder and select "Remove Folder from Project".

Please remove this bug.

**Comment by UltraInstinct05** [comment]
A bit late to the party, but essentially you can write a simple listener for this.

```python
import os
import sublime
import sublime_plugin

class RemoveFolderListener(sublime_plugin.EventListener):

    def on_post_window_command(self, window, command_name, args):
        if command_name == "delete_folder":
            for folder in window.project_data()["folders"]:
                if not os.path.exists(folder["path"]):
                    window.run_command("remove_folder", { "dirs": [folder["path"]] })
```

So the idea being, if a `delete_folder` command is issued, we listen for it in `on_post_window_command` and then scan the top level folders in the sidebar to see if they still exist. Obviously, when a top level folder is deleted, it no longer exists on the file system, so we simply use the `remove_folder` command to remove it (which is essentially the command behind `Remove Folder from Project`)

**Comment by braver** [comment]
Excellent suggestion, thanks!
