### ISSUE TITLE
Delete folder weirdness

### ISSUE THREAD

**Issue by pzac** [braver/SideBarTools#41]
If I delete a folder via the sidebar then the `*.sublime-project` file content gets commented out. I'm wondering if that  is due to the interaction with other packages.

Steps to replicate:

1. Open a sublime project
2. Right click on a directory in the sidebar and select "Delete folder"
3. Click OK

The sidebar collapses and foobar.sublime-project file now becomes

```
{
	/*"folders":
	[
		{
			"path": "~/code/foobar"
		}
	]*/
}
```
Is it only me?

**Comment by braver** [comment]
Don't believe that's something we do. I also can't reproduce it. You need to look at your other packages to see why that happens.
