### ISSUE TITLE
Add Edit action

### ISSUE THREAD

**Issue by PetrKryslUCSD** [braver/SideBarTools#47]
I implemented this (in about ten minutes; wow!). This is very effective when using
ST on a tablet. It is very difficult to double click with a finger, so I right click and choose Edit to open a file from the sidebar.

Would you entertain a PR?

**Comment by braver** [comment]
Sure why not! I would say it's a bit niche though, so I would prefer to have it behind a setting. Context menu's tend to get very crowded, so being able to disable some less-used ones would be beneficial. At some point we should consider giving full control over which commands to have in the menu... although it would require "proxy" commands for each one. Err... just a single setting for this would do just as well. 

Anyway, if you're up for it, I'd love a contribution here.
