### ISSUE TITLE
Commit 4645f59  remove Copy Absolute Path >= 4158 (sidebar only) causing errors in Sublime Text 3 (build 3211)

### ISSUE THREAD

**Issue by aafulei** [braver/SideBarTools#49]
In case you still hope to support ST3, which I would appreciate so much --

Commit 4645f59 that `remove Copy Absolute Path >= 4158 (sidebar only)`

```py
    def is_visible(self, paths=[], trigger=""):
        # in 4158 ST gets the "copy path" sidebar context entry
        # we want to keep our command palette entry though
        if trigger != 'palette' and int(sublime.version()) >= 4158:
            return False
        return super().is_visible(paths)
```

is causing errors in Sublime Text 3 (build 3211) -

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/aa/Library/Application Support/Sublime Text 3/Installed Packages/SideBarTools.sublime-package/SideBar.py", line 105, in is_visible
TypeError: is_visible() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by braver** [comment]
Oh, that's unintended, although admittedly this package is no longer ever tested on v3. Let's see what we can do about that...

**Comment by braver** [comment]
I tagged a version that should still be ST3 compatible and it [should appear as an update for those users](https://github.com/wbond/package_control_channel/pull/8838). That should resolve it. If not, there is a chance that reinstalling the package does work.
