### ISSUE TITLE
Commands from right-click context menu for tabs do not seem to work

### ISSUE THREAD

**Issue by mjklemm** [braver/SideBarTools#50]
When right clicking on a tab and then selecting any of the SideBarTools commands (e.g., "Copy Filename"), I'm getting this Python exception in ST3:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1505, in is_visible_
    ret = self.is_visible()
  File "C:\Users\micha\AppData\Roaming\Sublime Text 3\Installed Packages\SideBarTools.sublime-package\SideBar.py", line 105, in is_visible
TypeError: is_visible() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1657, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'context'
```

Looking at SideBar.py:105, it seems like there's a conflict between calling `is_visible` from the `SideBarCommand` class vs. `is_visible` from the `MultipleFilesMixin` class.

This is with SideBarTools 1.12.0 and ST build 4152 on Windows.

**Comment by mjklemm** [comment]
I'm not a real Python programmer, but I have debugged a bit, and it seems like Python cannot call the right method, unless the order of the base classes is swapped.  

```Python
class Mixin(object):
    def method(self, paths=[]):
        print(f'Mixin.method: {paths}')

class BaseClass(object):
    def method(self, paths=[], context=''):
        print(f'BaseClass.method: {paths} {context}')

class MyClass(Mixin, BaseClass):
    def method(self, paths=[], context=''):
        super().method(paths, context)

myclass = MyClass()
myclass.method(['a', 'b', 'c'], 'foobar')
```

This code snippet gives me a very similar error unless I define `MyClass(BaseClass, Mixin)`, in which case I seem to no longer be able to call `method()` from the `Mixin` class.

**Comment by braver** [comment]
Sorry, I guess I didn't test that properly, I was to focused on the command appearing properly and didn't check if they all worked. Should be better in the next release tag.
