### ISSUE TITLE
 Operations act on focused tab, not clicked tab

### ISSUE THREAD

**Issue by mozartilize** [braver/SideBarTools#51]
Might be you interest in https://github.com/sigsergv/SublimeFileOpTabContextMenu/issues/3

**Comment by braver** [comment]
Thanks for pointing me to a solution. I had noticed the issue before, but hadn’t figured out what to do about it yet.

**Comment by braver** [comment]
Note to self: https://github.com/sigsergv/SublimeFileOpTabContextMenu/commit/66854fd4fb790208151931194c1b000a64f3f31a#diff-19279e4c9cc5339f10e07c0f0e8da25d716ccb17bd9c3b64b066f90f842775a0
