### ISSUE TITLE
add delete file function 

### ISSUE THREAD

**Issue by adrian-gierakowski** [braver/SideBarTools#52]
to side bar and command pallet

**Comment by braver** [comment]
Sublime already comes with a delete option in the sidebar. Via the palette would be something new, I can see how that could be useful 👍🏻

**Comment by adrian-gierakowski** [comment]
Thanks, I’ve just migrated from https://packagecontrol.io/packages/SideBarEnhancements which added Delete to the palet and I used to use it quite a bit
