### ISSUE TITLE
Add setting to copy unix-style relative path on Windows

### ISSUE THREAD

**Issue by zigi05** [braver/SideBarTools#53]
Is it possible to add a setting to copy Unix style path on windows when clicking "Copy Relative Path" in context menu?

So as to have "path/like/this" copied on Windows, instead of "path\like\this".

**Comment by braver** [comment]
We could perhaps introduce a setting that make it always return a unix style path.. I presume that would be to use those paths inside WSL?

**Comment by zigi05** [comment]
> We could perhaps introduce a setting that make it always return a unix style path.. I presume that would be to use those paths inside WSL?

Yes, that what I meant - to introduce a setting like `copy_path_style: "unix"|"system"` for example, so I could enable it on Windows.

**Comment by braver** [comment]
@zigi05 There is a [new setting](https://github.com/braver/SideBarTools/blob/master/SideBarTools.sublime-settings#L17) you can set to true. This will expose new commands in the side bar (and the command palette and elsewhere) to copy the selection's relative path, but converted to POSIX format:

<img width="396" alt="Scherm­afbeelding 2024-07-18 om 20 13 42" src="https://github.com/user-attachments/assets/9343ac08-d4f9-4961-8cbf-534ce91d42e2">

I'll be tagging a new release later this evening, it should become available to you in a few hours.
