### ISSUE TITLE
Feature Request: Reveal in Finder for Directories

### ISSUE THREAD

**Issue by ghost** [braver/SideBarTools#6]
Not sure if this is something you want for this package, but I'll create this issue to start the discussion anyway 😄 

---

It's simple to reveal a file in the Finder/Native Manager by right-clicking on a file, but the option doesn't exist when right-clicking on directories.

Looks like others have desired this as well in core:

* http://sublimetext.userecho.com/topics/2672-reveal-direcotry-in-finder/

And here's what looks to be a solution (for ST2, not sure if we need to update it for ST3):

* https://gist.github.com/akuzemchak/1143963

Is this something we'd like to add to this package? Or should I make another request on the core?

**Comment by ghost** [comment]
Actually, this can probably be closed, since the [Open in Default Application](https://packagecontrol.io/packages/Open%20in%20Default%20Application) performs the same action and is included here - sorry for the noise. 👍

**Comment by braver** [comment]
Yeah, it’s kind of a hidden trick even with Open in Default Application. I should make a Readme note about it. That package isn’t included by the way, but definitely recommended.
